### ISSUE TITLE
Does lung segmentation help?

### ISSUE THREAD

**Issue by AlibekJ** [a-i-joe/auckland-ai-meetup-x-triage#4]
Intuitively I feel that instead of feeding raw image, cutting out lungs and rescaling them to the maximum resolution would yield better results.
Any thoughts?
Perhaps feeding in right and left lungs individually would also be a good idea?
https://dl.dropboxusercontent.com/u/8557832/lungs.png

**Comment by sorenbouma** [comment]
I think this is a smart idea, we want lots of detail, but large images will be slow to train so it makes sense to crop out as much as possible. It might be a bit tricky accurately segmenting the lungs though, only the china dataset seems to have labels with the outlines of lungs. Any ideas?

Feeding each lung in seperately I'm not sure about, party because this might make it harder to detect asymmetries and partly because the heart is only on the persons left, so each lung might require different features. I'm not sure whether this is important, perhaps it would be good to contact someone with domain knowledge?

**Comment by AlibekJ** [comment]
> only the china dataset seems to have labels with the outlines of lungs

Can you share the dataset with outlines?

I have got only NLM Montgomery dataset with lung outlines, 138 images in 4K resolution.
Using unet + opencv to cut out the lungs, couple days away from getting it done.

**Comment by sorenbouma** [comment]
Sorry my bad, it's only the NLM Montgomery set that has outlines. Do you have a plan for segmenting/cropping the x-rays in the large dataset, which aren't labelled with outlines?

**Comment by AlibekJ** [comment]
Yes, trained unet on the NLM dataset and it cuts lungs from arbitrary images. 
However, my segmenter is not yet as good as this one:
http://imlab.grid.by/appsegmxr/

BTW: another dataset (seems to have no restrictions on distribution):
http://imlab.grid.by/dataset-tb5classes/
Can't figure out a way of downloading it.

**Comment by AlibekJ** [comment]
Now can center lungs and resize to max resolution. Yet to test how much this improves the results.
![mcucxr_0003_0](https://cloud.githubusercontent.com/assets/8142809/25783677/908bf894-3371-11e7-8a5a-5c5d5a45179b.png)

**Comment by AlibekJ** [comment]
I observe substantial improvement with segmented images.

**Comment by a-i-joe** [comment]
Nice one!

**Comment by GregTarr** [comment]
Yep - intuitively I think cropping the images like this will help with this classification task.
To make the diagnoses included in the datasets you only need the images of the lungs. 

The amount of 'non-lung' image can be variable - because the radiographer (like a photographer who takes the x-rays) wants to capture the image of the whole lungs, but often this needs coordination with a patient who is unwell and can't take a good breath or stay still or even understand.

The broader clinical task of using chest radiographs in diagnosis uses the cropped elements - looking for things like rib fractures, ruptured bowel, changes in the bone or evidence of weight loss in patients with cancer to name a few. These other findings are less frequent than the diagnostic elements labelled in the included datasets.
